import wave
import string
import json
import re

from bisect import bisect
from fuzzysearch import find_near_matches
from vosk import Model, KaldiRecognizer, SetLogLevel
import Word as custom_Word

sceneData = [
['dialogue', 's1_001_judge', 'Judge', 'Court is back in session for the trial of Ms. Sweetie Belle. I trust that the defendant is ready to testify?', 'NONE'],
['dialogue', 's1_002_sweetie belle', 'Sweetie Belle', 'Yes, Your Honor.', 'NONE'],
['dialogue', 's1_003_judge', 'Judge', 'Before we begin, I would like to ask if either the prosecution or defense have any final objections to the matter. Prosecutor Luna, what say you?', 'NONE'],
['dialogue', 's1_004_athena', 'Athena', '(Having Sweetie Belle testify must have thrown her entire plan for a loop.)', 'NONE'],
['dialogue', 's1_005_judge', 'Judge', 'Prosecutor Luna? You… appear somewhat hesitant.', 'NONE'],
['dialogue', 's1_006_luna', 'Luna', '… Hmm. Those eyes of yours have not dwindled with age, Your Honor. ', 'NONE'],
['dialogue', 's1_007_luna', 'Luna', 'To be perfectly frank, I… am a bit hesitant. I cannot foresee where exactly this testimony will lead us. ', 'NONE'],
['dialogue', 's1_008_athena', 'Athena', 'Prosecutor Luna?', 'NONE'],
['dialogue', 's1_009_luna', 'Luna', 'Yes, Ms. Cykes?', 'NONE'],
['dialogue', 's1_010_athena', 'Athena', 'Do you remember what you told me last night? ', 'NONE'],
['dialogue', 's1_011_luna', 'Luna', 'But, still, I believe you must, if nothing else, trust that, in the end, the truth WILL be found. Never mind what the Lawkeeper has said.', 'NONE'],
['dialogue', 's1_012_athena', 'Athena', 'I know, but… it’s hard, sometimes. Like stumbling around in the dark hoping you’ll find a light switch. Except you don’t know if the room you’re in even has one. ', 'NONE'],
['dialogue', 's1_013_luna', 'Luna', 'Trust is a leap of faith, Athena. That’s all it ever is.', 'NONE'],
['dialogue', 's1_014_luna', 'Luna', '… I do, yes. ', 'NONE'],
['dialogue', 's1_015_athena', 'Athena', 'You trusted me back then. Asked me to find the truth, in any way that I can. Please. Trust me now.', 'NONE'],
['dialogue', 's1_016_luna', 'Luna', '… I shall, then, Ms. Cykes.', 'NONE'],
['dialogue', 's1_017_athena', 'Athena', '(I’d ask you to trust me as well, Sweetie Belle… But I somehow doubt you will.)', 'NONE'],
['dialogue', 's1_018_luna', 'Luna', 'Your Honor, the prosecution is ready to hear the witness’s testimony.', 'NONE'],
['dialogue', 's1_019_athena', 'Athena', 'As is the defense.', 'NONE'],
['dialogue', 's1_020_judge', 'Judge', 'Very well. Witness, you will testify to the court as to your movements on the night of the murder.', 'NONE'],
['dialogue', 's1_021_sweetie belle', 'Sweetie Belle', '…', 'NONE'],
['dialogue', 's1_022_sweetie belle', 'Sweetie Belle', 'There isn’t really a lot to say. That night, I was at the statue of Nightmare Moon.', 'NONE'],
['dialogue', 's1_023_sweetie belle', 'Sweetie Belle', 'Not long after I’d arrived, I saw timberwolves approaching the area. ', 'NONE'],
['dialogue', 's1_024_sweetie belle', 'Sweetie Belle', 'One of them attacked me! I managed to scare it off, and afterwards, I hid behind the statue.', 'NONE'],
['dialogue', 's1_025_sweetie belle', 'Sweetie Belle', 'I was there for a long time… I don’t really remember for how long, exactly. It’s all a bit of a blur.', 'NONE'],
['dialogue', 's1_026_sweetie belle', 'Sweetie Belle', 'After a while, I left the statue, seeing that no one was around. I made myself a tourniquet and went to Zecora’s hut to look for a healing potion.', 'NONE'],
['dialogue', 's1_027_judge', 'Judge', 'W-wait a moment! You mean to say—you were almost killed that night by wild timberwolves?', 'NONE'],
['dialogue', 's1_028_sweetie belle', 'Sweetie Belle', 'Y-yeah…', 'NONE'],
['dialogue', 's1_029_judge', 'Judge', 'My word! I knew those animals were brutes, but I never imagined they’d go so far as to attack a random filly! ', 'NONE'],
['dialogue', 's1_030_judge', 'Judge', 'To think there could be a place so full of danger in this world, let alone one so close to somewhere as idyllic as Ponyville!', 'NONE'],
['dialogue', 's1_031_athena', 'Athena', '(Hmm? What’s up with Prosecutor Luna?)', 'NONE'],
['dialogue', 's1_032_luna', 'Luna', 'It… is indeed fortunate that the bell did not toll for thee, young one.', 'NONE'],
['dialogue', 's1_033_athena', 'Athena', '… ', 'NONE'],
['dialogue', 's1_034_judge', 'Judge', 'In any case, I believe we may now begin the cross-examination. Defense, are you ready?', 'NONE'],
['dialogue', 's1_035_athena', 'Athena', 'You bet, Your Honor!', 'NONE'],
['dialogue', 's1_036_sweetie belle', 'Sweetie Belle', 'There isn’t really a lot to say. That night, I was at the statue of Nightmare Moon.', 'NONE'],
['dialogue', 's1_037_athena', 'Athena', 'HOLD IT! Why were you in the Everfree Forest in the first place? And why the statue?', 'NONE'],
['dialogue', 's1_038_sweetie belle', 'Sweetie Belle', 'Do I really have to say it?', 'NONE'],
['dialogue', 's1_039_athena', 'Athena', 'Yes, you do.', 'NONE'],
['dialogue', 's1_040_sweetie belle', 'Sweetie Belle', 'Fine. It was because I found Scootaloo’s note in Carousel Boutique.', 'NONE'],
['dialogue', 's1_041_judge', 'Judge', 'Scootaloo’s note?', 'NONE'],
['dialogue', 's1_042_athena', 'Athena', 'This one, Your Honor. It’s Scootaloo’s confession to Rarity for taking a roll of golden silk in order to fulfill the blackmailers’ demand. ', 'NONE'],
['dialogue', 's1_043_sweetie belle', 'Sweetie Belle', 'After I’d found that note, I considered following her and Turning into the forest to stop them.', 'NONE'],
['dialogue', 's1_044_athena', 'Athena', 'And why was that?', 'NONE'],
['dialogue', 's1_045_sweetie belle', 'Sweetie Belle', 'To get back that roll of golden silk, obviously! That thing cost Rarity a small fortune! And Scootaloo stole it right from under my nose!', 'NONE'],
['dialogue', 's1_046_sweetie belle', 'Sweetie Belle', 'I didn’t want Rarity to find out, or she’d totally freak! And I didn’t want Scootaloo to do anything dumb… Or anything MORE dumb than stealing from my sister!', 'NONE'],
['dialogue', 's1_047_athena', 'Athena', 'But how did you end up at the statue?', 'NONE'],
['dialogue', 's1_048_sweetie belle', 'Sweetie Belle', 'Once I finally decided to go after them, I headed to the forest entrance. As soon as I got there, I heard a loud noise coming from within.', 'NONE'],
['dialogue', 's1_049_sweetie belle', 'Sweetie Belle', 'I thought it might be her, so I cast an illumination spell and started heading towards it.', 'NONE'],
['dialogue', 's1_050_athena', 'Athena', 'Could you describe this noise for us?', 'NONE'],
['dialogue', 's1_051_sweetie belle', 'Sweetie Belle', 'It was loud, and metallic—like a clang. ', 'NONE'],
['dialogue', 's1_052_athena', 'Athena', 'A… clang?', 'NONE'],
['dialogue', 's1_053_twilight', 'Twilight', 'Hmm… That noise seems to be at the center of everything. Zecora and Diamond Tiara heard one, and Silver Spoon heard two…', 'NONE'],
['dialogue', 's1_054_athena', 'Athena', 'And Scootaloo heard two as well. This must have been one of them. ', 'NONE'],
['dialogue', 's1_055_athena', 'Athena', '(And if one was quieter than the other…)', 'NONE'],
['dialogue', 's1_056_athena', 'Athena', 'Sweetie Belle, around what time did you hear that clang?', 'NONE'],
['dialogue', 's1_057_sweetie belle', 'Sweetie Belle', 'Uh… probably around 10:15. Yeah, that sounds right. ', 'NONE'],
['dialogue', 's1_058_athena', 'Athena', '(10:15… the same time that Zecora, Diamond Tiara, and Silver Spoon each heard one.) ', 'NONE'],
['dialogue', 's1_059_athena', 'Athena', '(And when Sugar Stamp kicked Royal Order… if that “confession” wasn’t a load of baloney, that is.)', 'NONE'],
['dialogue', 's1_060_luna', 'Luna', 'Let’s get back to the testimony. Witness, what happened next?', 'NONE'],
['dialogue', 's1_061_sweetie belle', 'Sweetie Belle', 'Not long after I’d arrived, I saw timberwolves approaching the area. ', 'NONE'],
['dialogue', 's1_062_athena', 'Athena', 'HOLD IT! So the timberwolves were in the area when you arrived at the statue, and started to approach?', 'NONE'],
['dialogue', 's1_063_sweetie belle', 'Sweetie Belle', 'Yes, that’s correct.', 'NONE'],
['dialogue', 's1_064_athena', 'Athena', 'Did you see anything else near the statue besides those timberwolves?', 'NONE'],
['dialogue', 's1_065_sweetie belle', 'Sweetie Belle', 'Um… Yeah, actually. There was a big bloodstain out in front of the statue, and also a set of armor.', 'NONE'],
['dialogue', 's1_066_luna', 'Luna', 'That armor, no doubt, must have belonged to the Royal Order whom Scootaloo crashed into, and who crawled to the statue afterwards. ', 'NONE'],
['dialogue', 's1_067_athena', 'Athena', '(Except she claims that that Royal Order wasn’t wearing armor, so how did it get there?)', 'NONE'],
['dialogue', 's1_068_judge', 'Judge', 'And the bloodstain?', 'NONE'],
['dialogue', 's1_069_athena', 'Athena', 'Royal Order’s, of course. The blood test proved that. Sweetie Belle, was there a body present when you saw all of this?', 'NONE'],
['dialogue', 's1_070_sweetie belle', 'Sweetie Belle', 'No, there wasn’t a body.', 'NONE'],
['dialogue', 's1_071_athena', 'Athena', 'That means the timberwolves must have already eaten the body and were in the process of leaving when Sweetie Belle came along. ', 'NONE'],
['dialogue', 's1_072_luna', 'Luna', 'OBJECTION! But that contradicts what Sugar Stamp said. She saw Sweetie Belle trip Royal Order—the body had NOT yet been eaten by timberwolves.', 'NONE'],
['dialogue', 's1_073_athena', 'Athena', 'OBJECTION! However, as Fair Devotion suggested, it’s possible Sugar Stamp was misremembering things that night. ', 'NONE'],
['dialogue', 's1_074_athena', 'Athena', 'She might have been so traumatized that she only THOUGHT she saw Sweetie Belle trip him. ', 'NONE'],
['dialogue', 's1_075_luna', 'Luna', 'That still leaves Ms. Devotion’s testimony to contradict this one. Defense, tell me you have a plan for resolving that issue.', 'NONE'],
['dialogue', 's1_076_athena', 'Athena', 'I-I do, of course! Just, uh, hehe… don’t expect it right now, okay?', 'NONE'],
['dialogue', 's1_077_luna', 'Luna', 'I have a LOT of patience, Ms. Cykes. You needn’t worry.', 'NONE'],
['dialogue', 's1_078_athena', 'Athena', '(The only way to resolve it is to disprove both Sugar’s and Fair’s entire testimonies, which have been definitive since they back each other up.) ', 'NONE'],
['dialogue', 's1_079_athena', 'Athena', '(But in order to do that, I’ll first have to break Sweetie Belle’s testimony.)', 'NONE'],
['dialogue', 's1_080_judge', 'Judge', 'Witness, please continue.', 'NONE'],
['dialogue', 's1_081_sweetie belle', 'Sweetie Belle', 'One of them attacked me! I managed to scare it off, and afterwards, I hid behind the statue.', 'NONE'],
['dialogue', 's1_082_athena', 'Athena', 'HOLD IT! Were you injured by this attack?', 'NONE'],
['dialogue', 's1_083_sweetie belle', 'Sweetie Belle', 'A-A little bit. It scratched my right foreleg, enough for me to bleed a little.', 'NONE'],
['dialogue', 's1_084_luna', 'Luna', 'Which accounts for the fact that the witness’s blood was found at the scene.', 'NONE'],
['dialogue', 's1_085_athena', 'Athena', 'How did you scare off the timberwolf, exactly?', 'NONE'],
['dialogue', 's1_086_sweetie belle', 'Sweetie Belle', 'It was simple, really. I used the armor to do it. ', 'NONE'],
['dialogue', 's1_087_judge', 'Judge', ' What do you mean?', 'NONE'],
['dialogue', 's1_088_sweetie belle', 'Sweetie Belle', 'Timberwolves don’t like loud sounds. My friend Apple Bloom once told me about how her granny scared off a whole pack using nothing but a frying pan.', 'NONE'],
['dialogue', 's1_089_sweetie belle', 'Sweetie Belle', 'I remembered that story, and decided to do something similar with the armor. I took two pieces and hit them together as hard as I could!', 'NONE'],
['dialogue', 's1_090_sweetie belle', 'Sweetie Belle', 'That did the job, and scared them away!', 'NONE'],
['dialogue', 's1_091_judge', 'Judge', 'Hmm! A rather ingenious spur-of-the-moment idea!', 'NONE'],
['dialogue', 's1_092_athena', 'Athena', 'And around what time did you hit the armor pieces together?', 'NONE'],
['dialogue', 's1_093_sweetie belle', 'Sweetie Belle', 'Er… I’m not sure, to be honest.', 'NONE'],
['dialogue', 's1_094_athena', 'Athena', 'Well, let’s backtrack and see if we can figure it out. You heard the first clanging noise at 10:15, didn’t you?', 'NONE'],
['dialogue', 's1_095_sweetie belle', 'Sweetie Belle', 'Yes, that’s right.', 'NONE'],
['dialogue', 's1_096_athena', 'Athena', 'And afterwards, you started heading towards where you thought it was coming from—the statue. How long did it take you to arrive?', 'NONE'],
['dialogue', 's1_097_sweetie belle', 'Sweetie Belle', 'Probably… about ten minutes.', 'NONE'],
['dialogue', 's1_098_athena', 'Athena', 'Then we can reasonably assume that you arrived close to 10:25, if not on it. ', 'NONE'],
['dialogue', 's1_099_athena', 'Athena', 'You then hit the armor pieces together, maybe around the same time, eliciting a loud, clanging sound. ', 'NONE'],
['dialogue', 's1_100_athena', 'Athena', 'Does that sound about right, Sweetie Belle?', 'NONE'],
['dialogue', 's1_101_sweetie belle', 'Sweetie Belle', '…Yeah, it makes sense to me. ', 'NONE'],
['dialogue', 's1_102_athena', 'Athena', '(So one loud clang at 10:15, and the quieter one Sweetie caused at the statue around 10:25.)', 'NONE'],
['dialogue', 's1_103_athena', 'Athena', 'And afterwards, you chose to hide behind the statue. Why did you do that?', 'NONE'],
['dialogue', 's1_104_sweetie belle', 'Sweetie Belle', 'It’s because I thought I heard someone coming. And I was afraid it was more animals—more timberwolves, maybe, or a manticore, or something worse. ', 'NONE'],
['dialogue', 's1_105_sweetie belle', 'Sweetie Belle', 'So, I hid, using my magic to hide the blood trail that I left while walking behind the statue.', 'NONE'],
['dialogue', 's1_106_judge', 'Judge', 'And… what happened next?', 'NONE'],
['dialogue', 's1_107_sweetie belle', 'Sweetie Belle', 'I was there for a long time… I don’t really remember for how long, exactly. It’s all a bit of a blur.', 'NONE'],
['dialogue', 's1_108_athena', 'Athena', 'HOLD IT! You don’t remember how long you were back there? ', 'NONE'],
['dialogue', 's1_109_sweetie belle', 'Sweetie Belle', 'No, not at all. ', 'NONE'],
['dialogue', 's1_110_athena', 'Athena', '(She seems awfully calm about this whole thing…)', 'NONE'],
['dialogue', 's1_111_athena', 'Athena', 'You’re sure? You never saw whoever was coming your way?', 'NONE'],
['dialogue', 's1_112_sweetie belle', 'Sweetie Belle', 'Nope. To be honest, I don’t even fully remember what HAPPENED after. I think I must have passed out for a little while.', 'NONE'],
['dialogue', 's1_113_luna', 'Luna', 'Considering that you HAD just been attacked and were suffering some blood loss, that would indeed appear to be plausible. ', 'NONE'],
['dialogue', 's1_114_luna', 'Luna', 'We can’t expect you to remember how long you were out IF you were truly unconscious, after all.', 'NONE'],
['dialogue', 's1_115_athena', 'Athena', 'So you were out for a time, and then you came to. When you did, did you happen to see if the armor and bloodstain were still in front of the statue?', 'NONE'],
['dialogue', 's1_116_sweetie belle', 'Sweetie Belle', 'No, they were gone. ', 'NONE'],
['dialogue', 's1_117_athena', 'Athena', 'They were… gone? As in, they were just missing?', 'NONE'],
['dialogue', 's1_118_sweetie belle', 'Sweetie Belle', 'Yep. But I didn’t really think about it. I just wanted to get out of there.', 'NONE'],
['dialogue', 's1_119_judge', 'Judge', 'I understand, defendant. Let’s return to when you came to, then. What did you do immediately afterwards?', 'NONE'],
['dialogue', 's1_120_sweetie belle', 'Sweetie Belle', 'After a while, I left the statue, seeing that no one was around. I made myself a tourniquet and went to Zecora’s hut to look for a healing potion.', 'NONE'],
['dialogue', 's1_121_athena', 'Athena', 'OBJECTION! Sweetie Belle, you’re saying you made yourself a tourniquet, then made your way to Zecora’s hut. Is that correct?', 'NONE'],
['dialogue', 's1_122_sweetie belle', 'Sweetie Belle', 'Yeah, that’s what happened.', 'NONE'],
['dialogue', 's1_123_athena', 'Athena', 'I don’t think so. ', 'NONE'],
['dialogue', 's1_124_sweetie belle', 'Sweetie Belle', 'W-what?', 'NONE'],
['dialogue', 's1_125_athena', 'Athena', 'You made your tourniquet out of forest debris. And that, I’m afraid, would’ve been impossible for you.', 'NONE'],
['dialogue', 's1_126_judge', 'Judge', 'Why is that?', 'NONE'],
['dialogue', 's1_127_athena', 'Athena', 'Because, Your Honor—there’s no blood leading from the back of the statue TO the treeline. ', 'NONE'],
['dialogue', 's1_128_sweetie belle', 'Sweetie Belle', 'Gah!', 'NONE'],
['dialogue', 's1_129_luna', 'Luna', 'W-What the—', 'NONE'],
['dialogue', 's1_130_twilight', 'Twilight', 'You’re right! For Sweetie Belle to have gotten any materials to make a tourniquet, she’d have to grab stuff from the treeline! ', 'NONE'],
['dialogue', 's1_131_twilight', 'Twilight', 'But that would mean she’d be dripping blood all over the place!', 'NONE'],
['dialogue', 's1_132_athena', 'Athena', 'So, Sweetie Belle? How do you explain that?', 'NONE'],
['dialogue', 's1_133_sweetie belle', 'Sweetie Belle', 'T-that’s easy! I-I used my magic to keep the blood from falling everywhere!', 'NONE'],
['dialogue', 's1_134_athena', 'Athena', 'You used your magic? Why?', 'NONE'],
['dialogue', 's1_135_sweetie belle', 'Sweetie Belle', 'W-What do you mean why? I was BLEEDING!', 'NONE'],
['dialogue', 's1_136_athena', 'Athena', 'Exactly. You were injured, and bleeding. You’d just passed out and had only just awoken moments beforehand. Not the best condition to be using magic in.', 'NONE'],
['dialogue', 's1_137_athena', 'Athena', 'You’d probably be too rattled to be able to concentrate on making sure every drop of your blood didn’t end up on the forest floor. ', 'NONE'],
['dialogue', 's1_138_athena', 'Athena', 'So, again—why would you bother trying?', 'NONE'],
['dialogue', 's1_139_sweetie belle', 'Sweetie Belle', 'I… I… W-well, I just used my magic to grab stuff from the treeline to make a tourniquet!', 'NONE'],
['dialogue', 's1_140_twilight', 'Twilight', 'But that doesn’t add up either, Sweetie Belle. You and I both know that your magic hasn’t developed that much yet—', 'NONE'],
['dialogue', 's1_141_sweetie belle', 'Sweetie Belle', 'Yes it has! I’ve been practicing outside of our lessons! You just haven’t seen me!', 'NONE'],
['dialogue', 's1_142_twilight', 'Twilight', 'W-well, I can’t deny that, I suppose…', 'NONE'],
['dialogue', 's1_143_sweetie belle', 'Sweetie Belle', 'See! No matter how you look at it, I made that tourniquet!', 'NONE'],
['dialogue', 's1_144_athena', 'Athena', 'Oh? If that’s the case, then you should be able to recreate it for us, right now.', 'NONE'],
['dialogue', 's1_145_sweetie belle', 'Sweetie Belle', 'R-recreate it…?', 'NONE'],
['dialogue', 's1_146_judge', 'Judge', 'Defense, surely you’re not asking the defendant to go back into the Everfree Forest just to grab a bunch of… material? ', 'NONE'],
['dialogue', 's1_147_judge', 'Judge', 'And surely you don’t expect US to go in with her?', 'NONE'],
['dialogue', 's1_148_athena', 'Athena', 'O-of course not, Your Honor. Besides, I already have some forest debris here.', 'NONE'],
['dialogue', 's1_149_athena', 'Athena', 'With the court’s permission, I’d like to have Sweetie’s magic nullifier removed so she can recreate for us the tourniquet she claims to have made on that night.', 'NONE'],
['dialogue', 's1_150_judge', 'Judge', 'Agreed. Bailiff, remove the nullifier.', 'NONE'],
['dialogue', 's1_151_athena', 'Athena', 'Go on, Sweetie Belle, give it a try.', 'NONE'],
['dialogue', 's1_152_sweetie belle', 'Sweetie Belle', 'I… I can’t.', 'NONE'],
['dialogue', 's1_153_judge', 'Judge', 'Hm? Forgive me, witness. I believe I misheard you. Did you say you… can’t make a tourniquet?', 'NONE'],
['dialogue', 's1_154_athena', 'Athena', 'She did, Your Honor. ', 'NONE'],
['dialogue', 's1_155_luna', 'Luna', 'Then, how did she make one on the night she was attacked?', 'NONE'],
['dialogue', 's1_156_athena', 'Athena', 'She didn’t. Somepony else did. ', 'NONE'],
['dialogue', 's1_157_judge', 'Judge', 'But… Who?', 'NONE'],
['dialogue', 's1_158_athena', 'Athena', 'It might have been that somepony whom Sweetie Belle heard, just before she passed out behind the statue… or maybe—', 'NONE'],
['dialogue', 's1_159_sweetie belle', 'Sweetie Belle', 'W-wait!', 'NONE'],
['dialogue', 's1_160_judge', 'Judge', 'M-Ms. Sweetie Belle?', 'NONE'],
['dialogue', 's1_161_sweetie belle', 'Sweetie Belle', 'I-I remember, now! I-I didn’t make a tourniquet! I just used a bunch of stuff I’d collected and pressed against my wound to stop it from bleeding!', 'NONE'],
['dialogue', 's1_162_luna', 'Luna', '…You pressed unsanitized forest debris against an open wound? And trusted that it would keep it sealed long enough for you to reach Zecora’s hut?', 'NONE'],
['dialogue', 's1_163_sweetie belle', 'Sweetie Belle', 'Y-yeah… I-I mean, I knew that her hut was a little far, but I also knew that she had some healing potions I could use!', 'NONE'],
['dialogue', 's1_164_athena', 'Athena', 'If you knew that, does that also mean you knew where exactly she stored them? ', 'NONE'],
['dialogue', 's1_165_sweetie belle', 'Sweetie Belle', 'W-well, y-yeah, duh!', 'NONE'],
['dialogue', 's1_166_athena', 'Athena', 'Then could you please show the court from which cupboard you took that healing potion?', 'NONE'],
['dialogue', 's1_167_sweetie belle', 'Sweetie Belle', 'Umm… Uhh… H-here? T-this one?', 'NONE'],
['dialogue', 's1_168_athena', 'Athena', '… I’m sorry, Sweetie Belle. That is incorrect.', 'NONE'],
['dialogue', 's1_169_sweetie belle', 'Sweetie Belle', '!!', 'NONE'],
['dialogue', 's1_170_judge', 'Judge', '!!!', 'NONE'],
['dialogue', 's1_171_twilight', 'Twilight', 'I-it’s incorrect?! B-but how?!', 'NONE'],
['dialogue', 's1_172_athena', 'Athena', 'Because, that night, Sweetie Belle was neither the one to make the tourniquet, NOR the one to get the healing potion from Zecora. Somepony ELSE did both.', 'NONE'],
['dialogue', 's1_173_judge', 'Judge', 'B-but who? T-there was no one else at the statue!', 'NONE'],
['dialogue', 's1_174_luna', 'Luna', 'Hmm… I suspect Ms. Cykes has been building up to this moment for quite some time. ', 'NONE'],
['dialogue', 's1_175_luna', 'Luna', 'Well, then—why don’t you regale us? Who aided Ms. Sweetie Belle in both of these endeavors?', 'NONE'],
['dialogue', 's1_176_athena', 'Athena', '(The court wants an answer… So I’d better make this count. Let me think.) ', 'NONE'],
['dialogue', 's1_177_athena', 'Athena', '(The judge says no one else was at the statue besides Sweetie Belle. That much might be true… but there WERE other ponies in the forest that night.) ', 'NONE'],
['dialogue', 's1_178_athena', 'Athena', '(Given what we already know about this case, it stands to reason that her savior could be one of them.) ', 'NONE'],
['dialogue', 's1_179_athena', 'Athena', '(But, it can’t just be any of them. It’d have to be somepony who knows how to make a tourniquet AND identify which potions were healing ones.)', 'NONE'],
['dialogue', 's1_180_athena', 'Athena', '(And it can’t be Zecora, since she had no idea that the potion had been used until AFTER yesterday’s trial.)', 'NONE'],
['dialogue', 's1_181_athena', 'Athena', '(Which leaves us with a pony who has a fair bit of medical knowledge behind them, and who was in the forest that night. That can only mean—)', 'NONE'],
['dialogue', 's1_182_judge', 'Judge', 'Defense? Have you any idea as to who this mysterious helper was?', 'NONE'],
['dialogue', 's1_183_athena', 'Athena', 'I do, Your Honor. In fact, they’re in the lobby right now, ready to testify.', 'NONE'],
['dialogue', 's1_184_judge', 'Judge', 'And who are they?', 'NONE'],
['dialogue', 's1_185_athena', 'Athena', 'SILVER SPOON!', 'NONE'],
['dialogue', 's1_186_twilight', 'Twilight', '!! W-W—', 'NONE'],
['dialogue', 's1_187_judge', 'Judge', 'W-WHAT?!', 'NONE'],
['dialogue', 's1_188_athena', 'Athena', 'Not only was she in the forest that night, but she’s mentioned before that she has some light medical knowledge. ', 'NONE'],
['dialogue', 's1_189_athena', 'Athena', 'It’s not inconceivable that she might know how to make a rudimentary tourniquet.', 'NONE'],
['dialogue', 's1_190_sweetie belle', 'Sweetie Belle', 'N-no, wait! Y-you can’t call HER to the stand!', 'NONE'],
['dialogue', 's1_191_luna', 'Luna', 'Au contraire, Ms. Sweetie Belle. The defense has that right.', 'NONE'],
['dialogue', 's1_192_sweetie belle', 'Sweetie Belle', 'Nngh!', 'NONE'],
['dialogue', 's1_193_luna', 'Luna', 'And besides, I am… curious as to what Ms. Silver Spoon would have to say. ', 'NONE'],
['dialogue', 's1_194_judge', 'Judge', 'I would also like to hear from her. Bailiff, bring in Ms. Silver Spoon to testify before the court.', 'NONE'],
['dialogue', 's1_195_judge', 'Judge', 'Now, then, Ms. Silver Spoon—!! W-wait a moment, is that Ms. Diamond Tiara? What are YOU doing here? Only Ms. Silver Spoon was summoned!', 'NONE'],
['dialogue', 's1_196_diamond tiara', 'Diamond Tiara', 'Hmph! If you think I was gonna let Silvie face the courtroom alone, then you’re out of your old geezer mind!', 'NONE'],
['dialogue', 's1_197_luna', 'Luna', 'Ms. Diamond Tiara was quite insistent she accompany her friend, Your Honor. Her… loyalty is fairly sound. ', 'NONE'],
['dialogue', 's1_198_athena', 'Athena', '(Yes, I can see that… And her brattiness just as much.)', 'NONE'],
['dialogue', 's1_199_silver spoon', 'Silver Spoon', 'Um, Your Honor? Why WAS I asked to come back here? I already testified yesterday.', 'NONE'],
['dialogue', 's1_200_athena', 'Athena', 'We’d like to hear once again the actions you took on the night of Royal Order’s death, Silver Spoon.', 'NONE'],
['dialogue', 's1_201_diamond tiara', 'Diamond Tiara', 'W-What? But we already TOLD you everything that happened! Can’t you just look over the court transcripts? To save ponies like us from repeating ourselves? ?', 'NONE'],
['dialogue', 's1_202_athena', 'Athena', '(Silver Spoon looks like she’d rather be anywhere else but here. That must mean I’m on the right track.)', 'NONE'],
['dialogue', 's1_203_athena', 'Athena', 'Diamond Tiara, it’s the duty of a defense attorney to explore every possible avenue in a trial. ', 'NONE'],
['dialogue', 's1_204_athena', 'Athena', 'Even if it means treading on old ground, we can’t let that stop us. Not if doing so may allow us to see things a bit clearer.', 'NONE'],
['dialogue', 's1_205_luna', 'Luna', 'A bold sentiment—I concur.', 'NONE'],
['dialogue', 's1_206_silver spoon', 'Silver Spoon', 'P-Princess Luna?', 'NONE'],
['dialogue', 's1_207_luna', 'Luna', 'Both of you will testify as to the actions you took that night. Then we shall see if we can uncover anything new.', 'NONE'],
['dialogue', 's1_208_athena', 'Athena', '(In other words, she’s trusting that something DOES come out of this, and that I’m not just firing into the dark.)', 'NONE'],
['dialogue', 's1_209_silver spoon', 'Silver Spoon', 'Fine! We’ll tell you everything again. Right, DT?', 'NONE'],
['dialogue', 's1_210_diamond tiara', 'Diamond Tiara', 'H-Huh? O-Oh, right.', 'NONE'],
['dialogue', 's1_211_diamond tiara', 'Diamond Tiara', 'The two of us waited at the castle ruins for the CMC to show up, but it was only Scootaloo and her colt friend. He attacked me!', 'NONE'],
['dialogue', 's1_212_silver spoon', 'Silver Spoon', 'Afterwards, he threw DT’s crown into the gorge and ran off. We tried to follow, but DT stepped on my glasses, accidentally breaking them.', 'NONE'],
['dialogue', 's1_213_diamond tiara', 'Diamond Tiara', 'That crown is one of my most prized possessions! I couldn’t just leave it behind! So Silvie and I went down the gorge to go look for it!', 'NONE'],
['dialogue', 's1_214_silver spoon', 'Silver Spoon', 'When we came back, though, that was when we saw the body. We were also afraid the police might find the blackmail letter, so we tried looking for it, too.', 'NONE'],
['dialogue', 's1_215_diamond tiara', 'Diamond Tiara', 'But then that zebra came, so we hid. She saw the body and ran. After a bit, we followed after her, too.', 'NONE'],
['dialogue', 's1_216_judge', 'Judge', 'Hmm… Defense?', 'NONE'],
['dialogue', 's1_217_athena', 'Athena', 'Yes, Your Honor?', 'NONE'],
['dialogue', 's1_218_judge', 'Judge', 'That appears to indeed be a repeat of what we heard from these fillies in yesterday’s trial. I fail to see what use it may be.', 'NONE'],
['dialogue', 's1_219_athena', 'Athena', 'There might be a hole in it, Your Honor, especially since we now have heard other testimonies besides their own. ', 'NONE'],
['dialogue', 's1_220_judge', 'Judge', 'A fair point. Very well. You may begin your cross-examination.', 'NONE'],
['dialogue', 's1_221_diamond tiara', 'Diamond Tiara', 'The two of us waited at the castle ruins for the CMC to show up, but it was only Scootaloo and her colt friend. He attacked me!', 'NONE'],
['dialogue', 's1_222_athena', 'Athena', 'HOLD IT! I mean, it IS true that Turning Page attacked you, but, um… Well, it wasn’t like you were innocent bystanders, or anything. ', 'NONE'],
['dialogue', 's1_223_twilight', 'Twilight', 'Right. You two WERE blackmailing the Cutie Mark Crusaders in order to get that roll of golden fabric. ', 'NONE'],
['dialogue', 's1_224_diamond tiara', 'Diamond Tiara', 'W-well, yeah, b-but that doesn’t mean I should have been hit by a stupid wooden sword! Do you have any idea how PAINFUL it is? I’m lucky my nose didn’t break!', 'NONE'],
['dialogue', 's1_225_athena', 'Athena', '(I did see Mr. Wright take a hit. But something tells me he might be a bit more used to physical abuse than most.)', 'NONE'],
['dialogue', 's1_226_judge', 'Judge', 'And what happened afterward?', 'NONE'],
['dialogue', 's1_227_silver spoon', 'Silver Spoon', 'Afterwards, he threw DT’s crown into the gorge and ran off. We tried to follow, but DT stepped on my glasses, accidentally breaking them.', 'NONE'],
['dialogue', 's1_228_diamond tiara', 'Diamond Tiara', 'That crown is one of my most prized possessions! I couldn’t just leave it behind! So Silvie and I went down the gorge to go look for it!', 'NONE'],
['dialogue', 's1_229_athena', 'Athena', 'HOLD IT! You two went down into the gorge?', 'NONE'],
['dialogue', 's1_230_diamond tiara', 'Diamond Tiara', 'Well, yeah! That stupid colt threw away my crown! I couldn’t just leave it behind!', 'NONE'],
['dialogue', 's1_231_athena', 'Athena', 'I can understand you being able to go down there, Diamond Tiara, but what about you, Silver Spoon? How’d you go down there?', 'NONE'],
['dialogue', 's1_232_silver spoon', 'Silver Spoon', 'W-well, since my glasses were broken, I couldn’t see, so I needed Diamond Tiara to guide me down the steps.', 'NONE'],
['dialogue', 's1_233_athena', 'Athena', 'Could you add that to your testimony, then?', 'NONE'],
['dialogue', 's1_234_silver spoon', 'Silver Spoon', 'Uh, sure?', 'NONE'],
['dialogue', 's1_235_silver spoon', 'Silver Spoon', 'My glasses were broken, so I couldn’t see. Diamond Tiara had to guide me down the steps.', 'NONE'],
['dialogue', 's1_236_athena', 'Athena', 'OBJECTION! You’re saying that your glasses were broken? That doesn’t seem quite right to me, Silver Spoon.', 'NONE'],
['dialogue', 's1_237_silver spoon', 'Silver Spoon', 'Huh? But they WERE broken! It’s just like I told you yesterday during the trial!', 'NONE'],
['dialogue', 's1_238_luna', 'Luna', 'As I recall, defense, you were the ones to first postulate, based on the discovery of the glass shards, that glasses were indeed broken.', 'NONE'],
['dialogue', 's1_239_luna', 'Luna', 'We even verified that the shards belonged to Ms. Silver Spoon’s glasses during the recess.', 'NONE'],
['dialogue', 's1_240_athena', 'Athena', 'That is true, Prosecutor Luna, but there was a vital detail that I think you failed to mention as part of that report.', 'NONE'],
['dialogue', 's1_241_luna', 'Luna', 'What would that be?', 'NONE'],
['dialogue', 's1_242_athena', 'Athena', 'Those glass shards came from only ONE of Silver Spoon’s lenses. The other was completely intact. ', 'NONE'],
['dialogue', 's1_243_athena', 'Athena', 'Meaning that, with only HALF of her glasses broken, she could still see just fine through the other lens!', 'NONE'],
['dialogue', 's1_244_silver spoon', 'Silver Spoon', 'Ack!', 'NONE'],
['dialogue', 's1_245_athena', 'Athena', 'If you deny that, Silver Spoon, then I’m sure you wouldn’t mind if we verify with your doctor. ', 'NONE'],
['dialogue', 's1_246_athena', 'Athena', 'He could easily confirm that he replaced a pair of glasses with one of the lenses broken.', 'NONE'],
['dialogue', 's1_247_silver spoon', 'Silver Spoon', 'N-No, that won’t be necessary! It… It’s true. ', 'NONE'],
['dialogue', 's1_248_silver spoon', 'Silver Spoon', 'Only ONE of my lenses was broken, so I could still see. Well, uh, sort of. Enough that DT didn’t have to guide me blindly down the steps, at least.', 'NONE'],
['dialogue', 's1_249_judge', 'Judge', 'But that means that you stuck with your friend the whole time?', 'NONE'],
['dialogue', 's1_250_silver spoon', 'Silver Spoon', 'Y-yeah, of course! I was walking with only half a pair of glasses on, after all, and it was… still very dark and scary…', 'NONE'],
['dialogue', 's1_251_silver spoon', 'Silver Spoon', 'But, yeah, Athena’s right. I did have ONE lens letting me somewhat see. But I don’t see how this is important at all!', 'NONE'],
['dialogue', 's1_252_twilight', 'Twilight', 'Why IS this detail important, Athena?', 'NONE'],
['dialogue', 's1_253_athena', 'Athena', 'It’s because not only was Silver Spoon able to see while going down into the gorge, but she was also able to see coming out of it…', 'NONE'],
['dialogue', 's1_254_athena', 'Athena', '—and presumably for the rest of the night. Her being able to see at all gives a bit more credibility to my claim that she helped Sweetie Belle.', 'NONE'],
['dialogue', 's1_255_twilight', 'Twilight', 'You’re right! Wow, Athena, look at you! You’re really managing to put the pieces together!', 'NONE'],
['dialogue', 's1_256_athena', 'Athena', 'Hehe, thank you, Twilight. But we’ve still got a bit of ways to go before we can end this.', 'NONE'],
['dialogue', 's1_257_judge', 'Judge', 'In any case, I believe it is best that we return to the witness’s testimony, now that the matter about the glasses has been cleared up.', 'NONE'],
['dialogue', 's1_258_silver spoon', 'Silver Spoon', 'When we came back, though, that was when we saw the body. We were also afraid the police might find the blackmail letter, so we tried looking for it, too.', 'NONE'],
['dialogue', 's1_259_athena', 'Athena', 'HOLD IT! You two had gone down into the gorge, looking for Diamond Tiara’s crown. After you found it, you left. But during that time, did anything of note occur?', 'NONE'],
['dialogue', 's1_260_diamond tiara', 'Diamond Tiara', 'Of note? I mean, we DID hear that clang sound while we were looking for it.', 'NONE'],
['dialogue', 's1_261_athena', 'Athena', ' But there wasn’t just one clang heard that night, Diamond Tiara—there were, in fact, TWO. ', 'NONE'],
['dialogue', 's1_262_luna', 'Luna', 'Yes, we established that in the previous trial. ', 'NONE'],
['dialogue', 's1_263_luna', 'Luna', 'There was the one that Zecora, Diamond Tiara, and Silver Spoon heard, and then there was the one that Silver Spoon alone heard.', 'NONE'],
['dialogue', 's1_264_luna', 'Luna', 'It was suggested that it must have come from inside the castle—perhaps from something falling. ', 'NONE'],
['dialogue', 's1_265_athena', 'Athena', 'Suggested, yes, but not supported. However, that’s not my point. ', 'NONE'],
['dialogue', 's1_266_athena', 'Athena', 'Thanks to a little help from Scootaloo, as well as what we just heard from Sweetie Belle…', 'NONE'],
['dialogue', 's1_267_athena', 'Athena', 'I think I have a pretty good explanation for why Silver Spoon heard two, but Diamond Tiara did not. ', 'NONE'],
['dialogue', 's1_268_judge', 'Judge', 'Then, please explain, Ms. Cykes. ', 'NONE'],
['dialogue', 's1_269_athena', 'Athena', 'Before we resumed today’s trial, I asked Zecora and Scootaloo about those clangs. Zecora confirmed that she heard one before she left her hut. ', 'NONE'],
['dialogue', 's1_270_athena', 'Athena', 'Scootaloo said that she also heard one when she was passing by Zecora’s house. ', 'NONE'],
['dialogue', 's1_271_athena', 'Athena', 'But that night, she heard a SECOND clang—just before she crashed into Royal Order at the crossroads.', 'NONE'],
['dialogue', 's1_272_athena', 'Athena', 'Now, do you remember what we just heard from Sweetie Belle? What she did in order to scare off those timberwolves?', 'NONE'],
['dialogue', 's1_273_luna', 'Luna', 'She… banged the armor pieces together, making a clanging sound. ', 'NONE'],
['dialogue', 's1_274_athena', 'Athena', 'And that was, of course, AFTER Zecora had left her hut at 10:15. Sweetie hit the pieces together at around 10:25. ', 'NONE'],
['dialogue', 's1_275_athena', 'Athena', 'That’s why Zecora didn’t hear a second clang—she wasn’t nearby. ', 'NONE'],
['dialogue', 's1_276_silver spoon', 'Silver Spoon', 'Rgh… ', 'NONE'],
['dialogue', 's1_277_judge', 'Judge', 'So this second clang was heard by Ms. Scootaloo and Ms. Silver Spoon, then.', 'NONE'],
['dialogue', 's1_278_athena', 'Athena', 'That’s right, Your Honor. But, if you think about it, that shouldn’t be possible.', 'NONE'],
['dialogue', 's1_279_judge', 'Judge', 'Why is that?', 'NONE'],
['dialogue', 's1_280_athena', 'Athena', 'Scootaloo said she heard that clang when she was at the crossroads. And that clang came from Sweetie Belle, who was at the Nightmare Moon statue. ', 'NONE'],
['dialogue', 's1_281_athena', 'Athena', 'Looking at these two locations, we see that they’re within a short distance of each other. It’s not unreasonable that Scootaloo would have been able to hear it.', 'NONE'],
['dialogue', 's1_282_athena', 'Athena', 'Yet, Silver Spoon said that she heard the second clang as well—all the way from the other side of the forest, while she was in the gorge. ', 'NONE'],
['dialogue', 's1_283_athena', 'Athena', 'Now, how can THAT be?', 'NONE'],
['dialogue', 's1_284_judge', 'Judge', 'Y-you’re right! That does seem implausible! B-but she still said she heard that clang, so then—', 'NONE'],
['dialogue', 's1_285_athena', 'Athena', 'How could she have heard it? There’s only one explanation, Your Honor—Silver Spoon was not at the bottom of the gorge like she and Diamond Tiara claimed. ', 'NONE'],
['dialogue', 's1_286_athena', 'Athena', 'Instead, she was close enough to the statue to have heard that second clang!', 'NONE'],
['dialogue', 's1_287_silver spoon & s1_287_diamond tiara', 'Silver Spoon & Diamond Tiara', 'ARGH!/No…', 'NONE'],
['dialogue', 's1_288_athena', 'Athena', 'Your Honor, it’s the defense’s belief that instead of following Diamond Tiara down the gorge, Silver Spoon chased after Scootaloo and Turning Page. ', 'NONE'],
['dialogue', 's1_289_athena', 'Athena', 'She made her way through the forest, all the way to the crossroads, hearing both clangs along the way. ', 'NONE'],
['dialogue', 's1_290_athena', 'Athena', 'Once she got to the crossroads, she headed for the statue, where she found Sweetie Belle injured and unconscious.', 'NONE'],
['dialogue', 's1_291_athena', 'Athena', 'As I said before, Silver Spoon has a bit of background in medicine, since both of her parents are doctors. ', 'NONE'],
['dialogue', 's1_292_athena', 'Athena', 'She would have known how to make a tourniquet out of an assortment of items.Therefore, she would have known how to treat Sweetie Belle’s injury!', 'NONE'],
['dialogue', 's1_293_athena', 'Athena', 'And that explains away the issue from earlier—how Sweetie Belle, despite not knowing how to treat her wound, managed to have it treated in the first place!', 'NONE'],
['dialogue', 's1_294_luna', 'Luna', 'OBJECTION! This is truly a fascinating theory, defense! But you have yet to answer one final question regarding it!', 'NONE'],
['dialogue', 's1_295_luna', 'Luna', 'Why would she have found Sweetie Belle at all? ', 'NONE'],
['dialogue', 's1_296_judge', 'Judge', 'Prosecutor Luna, what do you mean?', 'NONE'],
['dialogue', 's1_297_luna', 'Luna', 'I can believe that Silver Spoon might have run all the way back to the crossroads, but why would she then head to the statue after getting there?', 'NONE'],
['dialogue', 's1_298_luna', 'Luna', 'Defense, give us some proof to show why she would’ve gone to the statue!', 'NONE'],
['dialogue', 's1_299_athena', 'Athena', 'Gladly, Prosecutor Luna! TAKE THAT!', 'NONE'],
['dialogue', 's1_300_judge', 'Judge', 'This is… Ah! The photo that Private Eye took, revealing Royal Order’s blood at the crossroads? ', 'NONE'],
['dialogue', 's1_301_athena', 'Athena', 'The very same, Your Honor. And if you’ll recall, that blood led to the Nightmare Moon statue. ', 'NONE'],
['dialogue', 's1_302_athena', 'Athena', 'If that blood was visible on the night in question, then Silver Spoon should have easily seen it! ', 'NONE'],
['dialogue', 's1_303_athena', 'Athena', 'And that would have meant she could have followed it to the statue, where she’d find Sweetie Belle!', 'NONE'],
['dialogue', 's1_304_athena', 'Athena', 'And after she did, she treated the young filly’s wound using what she had available!', 'NONE'],
['dialogue', 's1_305_silver spoon', 'Silver Spoon', 'OBJECTION!', 'NONE'],
['dialogue', 's1_306_athena', 'Athena', '?!', 'NONE'],
['dialogue', 's1_307_twilight', 'Twilight', '?!', 'NONE'],
['dialogue', 's1_308_luna', 'Luna', '?!', 'NONE'],
['dialogue', 's1_309_judge', 'Judge', 'M-Ms. Silver Spoon?', 'NONE'],
['dialogue', 's1_310_diamond tiara', 'Diamond Tiara', 'S-Silvie, what are you—', 'NONE'],
['dialogue', 's1_311_silver spoon', 'Silver Spoon', 'Y-Your Honor, I… I object!', 'NONE'],
['dialogue', 's1_312_judge', 'Judge', 'Y-yes, witness? W-what exactly are you objecting to?', 'NONE'],
['dialogue', 's1_313_silver spoon', 'Silver Spoon', 'I-I’m objecting… to what Athena said, about going to the statue and helping Sweetie Belle!', 'NONE'],
['dialogue', 's1_314_judge', 'Judge', 'Y-you are?', 'NONE'],
['dialogue', 's1_315_silver spoon', 'Silver Spoon', 'O-okay, I admit it! I… I didn’t exactly go down the gorge with DT when she needed me to! ', 'NONE'],
['dialogue', 's1_316_silver spoon', 'Silver Spoon', 'Instead, I DID chase after Scootaloo and Turning Page!', 'NONE'],
['dialogue', 's1_317_silver spoon', 'Silver Spoon', 'But that’s it! That’s all I did. I never went near that statue, and I NEVER helped Sweetie Belle! Not one bit!', 'NONE'],
['dialogue', 's1_318_twilight', 'Twilight', 'But then, how ELSE could Sweetie Belle have gotten the help she needed for her injury? ', 'NONE'],
['dialogue', 's1_319_twilight', 'Twilight', 'She couldn’t do it on her own, and Silver Spoon, you were the only one in the forest that night, sans Zecora, with the expertise needed to help her! ', 'NONE'],
['dialogue', 's1_320_silver spoon', 'Silver Spoon', 'I-I-I don’t know, Princess Twilight! But I still never did what Athena’s saying I did! ', 'NONE'],
['dialogue', 's1_321_silver spoon', 'Silver Spoon', 'A-and it’s not like she has any proof to back that up!', 'NONE'],
['dialogue', 's1_322_athena', 'Athena', '…', 'NONE'],
['dialogue', 's1_323_twilight', 'Twilight', 'Athena…? You’re thinking of something, aren’t you?', 'NONE'],
['dialogue', 's1_324_athena', 'Athena', 'I am. I have a pretty good idea of how to show definitively that Silver Spoon DID help Sweetie Belle that night. But… I don’t think I want to do that just yet.', 'NONE'],
['dialogue', 's1_325_twilight', 'Twilight', 'W-what? But, shouldn’t we? ', 'NONE'],
['dialogue', 's1_326_athena', 'Athena', 'We should, but there’s another angle in all of this that I feel needs to be established BEFORE I do that. ', 'NONE'],
['dialogue', 's1_327_athena', 'Athena', 'We know that Silver Spoon’s not telling the truth, and it’d be very easy to show that. But we also know Sweetie Belle’s been lying to us.', 'NONE'],
['dialogue', 's1_328_athena', 'Athena', 'I think… I think there’s a way to get the BOTH of them to confess the truth. Kill two birds with one stone. ', 'NONE'],
['dialogue', 's1_329_athena', 'Athena', 'And I think, if we do that, we’ll be one step closer to figuring out everything.', 'NONE'],
['dialogue', 's1_330_twilight', 'Twilight', 'You really think so?', 'NONE'],
['dialogue', 's1_331_athena', 'Athena', 'Yeah. I’m more certain of it than I’ve ever been, Twilight.', 'NONE'],
['dialogue', 's1_332_twilight', 'Twilight', '… All right, Athena. I’ll follow your lead.', 'NONE'],
['dialogue', 's1_333_judge', 'Judge', 'Defense? This witness has objected to your claim. Do you have any proof to support it?', 'NONE'],
['dialogue', 's1_334_athena', 'Athena', 'I do, Your Honor—but, I don’t want to present it at this moment. ', 'NONE'],
['dialogue', 's1_335_judge', 'Judge', 'Y-You don’t WANT to present it? Ms. Cykes, I’m afraid I don’t understand.', 'NONE'],
['dialogue', 's1_336_athena', 'Athena', 'Your Honor, there’s one more detail that I would like to get an explanation for, from Ms. Silver Spoon. ', 'NONE'],
['dialogue', 's1_337_judge', 'Judge', 'O-One more detail…', 'NONE'],
['dialogue', 's1_338_luna', 'Luna', 'Ms. Cykes.', 'NONE'],
['dialogue', 's1_339_athena', 'Athena', 'Yes, Prosecutor Luna?', 'NONE'],
['dialogue', 's1_340_luna', 'Luna', 'We have a saying here in Equestria. ', 'NONE'],
['dialogue', 's1_341_luna', 'Luna', 'Be wary of those who lead you down the garden path, promising a way out through the twists and turns. ', 'NONE'],
['dialogue', 's1_342_luna', 'Luna', 'So far, you have been objecting at various points during this trial, hinting, it would seem, at some larger explanation—but, you have yet to provide one. ', 'NONE'],
['dialogue', 's1_343_luna', 'Luna', 'Where there were clear avenues for you to exploit, you chose instead to take multiple twisting paths, stringing the court along. ', 'NONE'],
['dialogue', 's1_344_luna', 'Luna', 'So, I must ask—where are you taking us? Is it another garden path?And when will these many winding roads cease, allowing us clear passage? ', 'NONE'],
['dialogue', 's1_345_athena', 'Athena', '… I understand if you feel as though I’ve been leading us nowhere, Prosecutor Luna. But, this will be the last time I take us down those winding roads. ', 'NONE'],
['dialogue', 's1_346_athena', 'Athena', 'I promise. ', 'NONE'],
['dialogue', 's1_347_luna', 'Luna', '…', 'NONE'],
['dialogue', 's1_348_judge', 'Judge', 'What is this one other detail that you had in mind, Ms. Cykes?', 'NONE'],
['dialogue', 's1_349_athena', 'Athena', 'It’s something that’s been bothering me from the very beginning of this entire case, Your Honor, almost as much as Royal Order’s death.', 'NONE'],
['dialogue', 's1_350_athena', 'Athena', 'The item that got Turning Page arrested.', 'NONE'],
['dialogue', 's1_351_twilight', 'Twilight', 'You mean…', 'NONE'],
['dialogue', 's1_352_athena', 'Athena', 'That’s right. The anonymous tip.', 'NONE'],
['dialogue', 's3_001_twilight', 'Twilight', 'I\'m still SO impressed with this technology, Athena. It\'s amazing!', 'NONE'],
['dialogue', 's3_002_athena', 'Athena', 'Heh. That\'s my mother for you. She and the engineer she worked with were a great team.', 'NONE'],
['dialogue', 's3_003_athena', 'Athena', 'And it\'s thanks to them that we have the ability to clear up this testimony.', 'NONE'],
['dialogue', 's3_004_twilight', 'Twilight', 'That\'s... a lot of noise, though.', 'NONE'],
['dialogue', 's3_005_athena', 'Athena', 'Yeah. I expected as much. Ms. Devotion is desperately trying to keep everything under wraps. ', 'NONE'],
['dialogue', 's3_006_twilight', 'Twilight', 'But we can\'t let that stop us.', 'NONE'],
['dialogue', 's3_007_athena', 'Athena', 'And we won\'t. Time to kiss this noise goodbye!', 'NONE'],
['dialogue', 's3_008_athena', 'Athena', 'GOT IT! Ms. Devotion, this argument you had... It must have gotten you very angry.', 'NONE'],
['dialogue', 's3_009_fair_devotion', 'Fair Devotion', 'Obviously.', 'NONE'],
['dialogue', 's3_010_athena', 'Athena', 'And yet, I couldn\'t help but notice you sounded sad AND shocked, along with being angry. Is there any reason why that comes to mind?', 'NONE'],
['dialogue', 's3_011_fair_devotion', 'Fair Devotion', 'None whatsoever. Your little toy must be wrong. I distinctly recall being angry, and nothing else.', 'NONE'],
['dialogue', 's3_012_athena', 'Athena', '(That was, admittedly, a long shot... Especially since she\'s trying to cover everything up. Still, I wonder... What even incited the argument in the first place?)', 'NONE'],
['dialogue', 's3_013_athena', 'Athena', '(I know she said they didn\'t find anything, but what if they did? And what if it led to them talking about Turning Page?)', 'NONE'],
['dialogue', 's3_014_athena', 'Athena', 'At any rate, you say you were angry with Royal Order?', 'NONE'],
['dialogue', 's3_015_fair_devotion', 'Fair Devotion', 'Beyond angry. Furious, in fact--to the point that I didn\'t even have to think when I kicked him into the statue. ', 'NONE'],
['dialogue', 's3_016_athena', 'Athena', '"Kicked" him? That\'s odd. If you kicked him hard enough for him to be impaled at the statue\'s base... then how do you explain this?', 'NONE'],
['dialogue', 's3_017_fair_devotion', 'Fair Devotion', '!! T-That\'s Royal\'s armor! ', 'NONE'],
['dialogue', 's3_018_athena', 'Athena', 'Indeed. But surely, looking at it, you can see why I\'d need an explanation for what we found on it?', 'NONE'],
['dialogue', 's3_019_fair_devotion', 'Fair Devotion', 'Rgh...', 'NONE'],
['dialogue', 's3_020_judge', 'Judge', 'Erm... Forgive me, Ms. Cykes. Could you explain to the court what you mean?', 'NONE'],
['dialogue', 's3_021_athena', 'Athena', 'Gladly, Your Honor. Look at the left side. You see that dent?', 'NONE'],
['dialogue', 's3_022_judge', 'Judge', 'I do...', 'NONE'],
['dialogue', 's3_023_athena', 'Athena', 'Does that dent look like it was made by a set of hooves?', 'NONE'],
['dialogue', 's3_024_judge', 'Judge', 'No... It looks more like something somewhat rectangular struck it.', 'NONE'],
['dialogue', 's3_025_athena', 'Athena', 'Exactly, Your Honor. Something rectangular--meaning, the dent could NOT have come from somepony kicking the armor, as Ms. Devotion has just claimed.', 'NONE'],
['dialogue', 's3_026_fair_devotion', 'Fair Devotion', 'Gnk!', 'NONE'],
['dialogue', 's3_027_judge', 'Judge', 'That\'s right! But then, how do you explain the dent?', 'NONE'],
['dialogue', 's3_028_athena', 'Athena', 'If Ms. Devotion can\'t, I think I can. Based on what the Mood Matrix revealed, and how I\'ve already claimed that Turning\'s the true culprit...', 'NONE'],
['dialogue', 's3_029_athena', 'Athena', '... then the object which formed this dent in the armor must have been... TAKE THAT! Turning\'s own wooden sword. ', 'NONE'],
['dialogue', 's3_030_fair_devotion', 'Fair Devotion', 'That\'s just not possible! Turning wasn\'t anywhere NEAR the Nightmare Night statue! Plus, he had his sword with him the whole night, remember?', 'NONE'],
['dialogue', 's3_031_fair_devotion', 'Fair Devotion', 'He certainly had it when he attacked Diamond Tiara. More than that, though--', 'NONE'],
['dialogue', 's3_032_athena', 'Athena', 'Let me finish for you, Ms. Devotion. You\'re about to say that, afterwards, Turning COULDN\'T have used his sword. Is that right?', 'NONE'],
['dialogue', 's3_033_fair_devotion', 'Fair Devotion', '!!', 'NONE'],
['dialogue', 's3_034_judge', 'Judge', 'Why do you say that, Ms. Cykes?', 'NONE'],
['dialogue', 's3_035_athena', 'Athena', 'Because, Your Honor, Turning\'s sword broke when he hit Diamond Tiara during the blackmail exchange. ', 'NONE'],
['dialogue', 's3_036_judge', 'Judge', 'It broke?', 'NONE'],
['dialogue', 's3_037_fair_devotion', 'Fair Devotion', 'Exactly my point! Even if Turning WAS near the statue, he could not have used his sword to attack Royal Order!', 'NONE'],
['dialogue', 's3_038_twilight', 'Twilight', 'That would appear to be the case, sure, but that becomes entirely irrelevant when we consider a couple of factors. ', 'NONE'],
['dialogue', 's3_039_fair_devotion', 'Fair Devotion', 'Irrelevant?!', 'NONE'],
['dialogue', 's3_040_twilight', 'Twilight', 'Right. Turning Page\'s a unicorn. You just admitted to us that he can teleport. ', 'NONE'],
['dialogue', 's3_041_twilight', 'Twilight', 'So... he could have used his magic to teleport to the statue at some point, bringing his sword with him.', 'NONE'],
['dialogue', 's3_042_athena', 'Athena', 'And more than that, he also could have used his magic to hold the pieces of his sword together, if he teleported there AFTER he attacked Diamond Tiara. ', 'NONE'],
['dialogue', 's3_043_athena', 'Athena', 'He could still have used the sword to attack Royal Order. It would have been just as effective in two pieces held together by magic as it would have been whole. ', 'NONE'],
['dialogue', 's3_044_fair_devotion', 'Fair Devotion', 'But teleporting to the statue would have required that he KNEW where the statue was. What proof is there that he\'d ever been there?', 'NONE'],
['dialogue', 's3_045_twilight', 'Twilight', 'That\'s easy. He would have gone there many times, thanks to a certain Nightmare Night tradition.', 'NONE'],
['dialogue', 's3_046_apple bloom', 'Apple Bloom', 'It\'s for Nightmare Night! It\'s a holiday where fillies and colts go from house-to-house collecting candy. ', 'NONE'],
['dialogue', 's3_047_apple bloom', 'Apple Bloom', 'And then, at the end of the night, we all come here, and give up some of our candy so that Nightmare Moon won\'t gobble us up!', 'NONE'],
['dialogue', 's3_048_athena', 'Athena', 'Since that tradition involves bringing candy to the statue, it\'s not unreasonable to think that, at some point, Turning would have visited it during the holiday. ', 'NONE'],
['dialogue', 's3_049_fair_devotion', 'Fair Devotion', 'Ngh!', 'NONE'],
['dialogue', 's3_050_athena', 'Athena', 'Your Honor, the defense requests that the dent in the armor be tested against the sword. I believe it will show that the two are a perfect match.', 'NONE'],
['dialogue', 's3_051_athena', 'Athena', 'I\'d also like to pause the current therapy session, until this test is done. Is that okay?', 'NONE'],
['dialogue', 's3_052_judge', 'Judge', 'Granted. And yes, that\'s fine by me. Prosecutor Luna?', 'NONE'],
['dialogue', 's3_053_luna', 'Luna', 'I see no problem with either of these requests.', 'NONE'],
['dialogue', 's3_054_judge', 'Judge', 'Very well. Bailiff, make haste with this test!', 'NONE'],
['dialogue', 's3_055_judge', 'Judge', 'Bailiff, what do the results say?', 'NONE'],
['dialogue', 's3_056_bailiff #1', 'Bailiff #1', 'It\'s as the defense claimed, Your Honor! The sword does match the shape of the dent found on the left side of the armor!', 'NONE'],
['dialogue', 's3_057_athena', 'Athena', 'Ms. Devotion, do you have an explanation for this?', 'NONE'],
['dialogue', 's3_058_fair_devotion', 'Fair Devotion', 'Fine. I concede. That sword... It was found at the statue. In fact, it was what started the argument in the first place. ', 'NONE'],
['dialogue', 's3_059_twilight', 'Twilight', 'If it was at the statue, then that must mean Turning Page had INDEED gone there that night. ', 'NONE'],
['dialogue', 's3_060_athena', 'Athena', 'Turning? ', 'NONE'],
['dialogue', 's3_061_turning page', 'Turning Page', 'Huh? Yes, Ms. Cykes?', 'NONE'],
['dialogue', 's3_062_athena', 'Athena', 'Before we continue with your mother\'s therapy session, I need to ask you something. Could you elaborate on what happened at the statue, exactly?', 'NONE'],
['dialogue', 's3_063_turning page', 'Turning Page', '... Y-yeah, sure. After Scootaloo and I left the blackmail deal, I wanted to get ahead of her, to make sure she\'d be okay. So I thought I\'d try and teleport.', 'NONE'],
['dialogue', 's3_064_turning page', 'Turning Page', 'But the problem was, I didn\'t know a lot of places in the forest. There was the bog, but that would have meant more time walking.', 'NONE'],
['dialogue', 's3_065_athena', 'Athena', 'So you chose to teleport to the statue?', 'NONE'],
['dialogue', 's3_066_turning page', 'Turning Page', 'Uh huh. I figured that, even if I had to walk back along the path to catch up to Scootaloo, it\'d still be faster than running the whole way. ', 'NONE'],
['dialogue', 's3_067_turning page', 'Turning Page', 'But, when I teleported to the statue, I heard voices coming. ', 'NONE'],
['dialogue', 's3_068_turning page', 'Turning Page', 'I recognized them--they were Mom and Dad\'s. And they were coming way too quickly for me to charge another teleport.', 'NONE'],
['dialogue', 's3_069_turning page', 'Turning Page', 'So, I ducked behind the statue to hide from them. But I forgot to take my sword with me. ', 'NONE'],
['dialogue', 's3_070_turning page', 'Turning Page', 'It was too late to grab it. I heard them come, and when they saw my sword, they began to argue.', 'NONE'],
['dialogue', 's3_071_fair_devotion', 'Fair Devotion', 'Is this...? Oh, no. No, no, no, please, NO!', 'NONE'],
['dialogue', 's3_072_royal order', 'Royal Order', 'Fair? What is it?', 'NONE'],
['dialogue', 's3_073_fair_devotion', 'Fair Devotion', 'His sword, Royal--I found his SWORD! You know he\'d never leave it behind, unless--unless--', 'NONE'],
['dialogue', 's3_074_royal order', 'Royal Order', 'Whoa, hang on a second. I\'m sure--I\'m sure nothing bad\'s happened to him. ', 'NONE'],
['dialogue', 's3_075_fair_devotion', 'Fair Devotion', '"Nothing bad?!" Are you serious? We\'re in the Everfree Forest! Nothing GOOD happens here!', 'NONE'],
['dialogue', 's3_076_royal order', 'Royal Order', 'Turning\'s a tough kid. He wouldn\'t let himself fall victim to some forest monster.', 'NONE'],
['dialogue', 's3_077_fair_devotion', 'Fair Devotion', 'Wouldn\'t let himself--do you hear yourself, Royal? If anything happened to Turning, it\'ll be your fault and you know it!', 'NONE'],
['dialogue', 's3_078_royal order', 'Royal Order', 'M-My fault? What are you talking about?!', 'NONE'],
['dialogue', 's3_079_fair_devotion', 'Fair Devotion', 'Oh, don\'t you play innocent with me! It\'s YOUR fault for insisting that you do all your training with him in this Celestia-forsaken forest! ', 'NONE'],
['dialogue', 's3_080_fair_devotion', 'Fair Devotion', 'If you hadn\'t done that--', 'NONE'],
['dialogue', 's3_081_royal order', 'Royal Order', 'If I hadn\'t done that, then Turning would not be ready to join the guard when the time comes!', 'NONE'],
['dialogue', 's3_082_fair_devotion', 'Fair Devotion', 'He\'s a CHILD, Royal! Stars above, how can you be BLIND to that!', 'NONE'],
['dialogue', 's3_083_royal order', 'Royal Order', 'I-I\'m not blind to that--', 'NONE'],
['dialogue', 's3_084_fair_devotion', 'Fair Devotion', 'Furthermore, do you have any idea how your "training" has been affecting him? Do you have any idea what he\'s done?', 'NONE'],
['dialogue', 's3_085_fair_devotion', 'Fair Devotion', 'He\'s got some reckless hero complex now! And I DO mean reckless! ', 'NONE'],
['dialogue', 's3_086_fair_devotion', 'Fair Devotion', 'Earlier he attacked Diamond Tiara and Silver Spoon--you remember them, don\'t you? Or at least, their parents?', 'NONE'],
['dialogue', 's3_087_royal order', 'Royal Order', 'Urgh, I do... ', 'NONE'],
['dialogue', 's3_088_fair_devotion', 'Fair Devotion', 'Then you shouldn\'t be surprised to know that just before you came home, that snobby Spoiled Rich ransomed us for all our savings, ', 'NONE'],
['dialogue', 's3_089_fair_devotion', 'Fair Devotion', 'In order to pay for the dresses our SON ruined!', 'NONE'],
['dialogue', 's3_090_fair_devotion', 'Fair Devotion', 'I had to cancel our Hearts and Hooves dinner just to start saving up enough money to pay her off--a dinner, may I remind you, that had been planned for a while!?', 'NONE'],
['dialogue', 's3_091_royal order', 'Royal Order', 'I... I just want to help Turning pursue his dream.', 'NONE'],
['dialogue', 's3_092_fair_devotion', 'Fair Devotion', 'Pursue his dream, sure! And how exactly are you doing that? Being away from home all the time? Not disciplining Turning when you ARE around?', 'NONE'],
['dialogue', 's3_093_royal order', 'Royal Order', 'You\'re making it sound like I\'m the only one who SHOULD be disciplining him! You\'re his mother!', 'NONE'],
['dialogue', 's3_094_fair_devotion', 'Fair Devotion', 'A mother whom he doesn\'t listen to, a mother whom he won\'t give even a moment\'s consideration, all because she wants him to attend school--THAT kind of mother?', 'NONE'],
['dialogue', 's3_095_royal order', 'Royal Order', "E-even so, Fair, you KNOW why I've had to work away from home more this past year. I can\'t just ignore my duties. Especially not now of all times!", 'NONE'],
['dialogue', 's3_096_fair_devotion', 'Fair Devotion', 'So you\'d choose your job over your own family?!', 'NONE'],
['dialogue', 's3_097_royal order', 'Royal Order', 'That\'s not fair, Fair... It\'s not that simple. Much as I\'d like it to be...', 'NONE'],
['dialogue', 's3_098_fair_devotion', 'Fair Devotion', 'This is exactly why Turning needs to be disciplined more--so that he can understand what it means to have MORE responsibility.', 'NONE'],
['dialogue', 's3_099_fair_devotion', 'Fair Devotion', 'No doubt what the Royal Guard will demand of him will be nothing compared to what it demanded of YOU back in your day.', 'NONE'],
['dialogue', 's3_100_royal order', 'Royal Order', 'You have NO idea what it demanded of me back in my day, Fair. Don\'t try and say that you do.', 'NONE'],
['dialogue', 's3_101_fair_devotion', 'Fair Devotion', 'And just what\'s THAT supposed to mean? Is this yet ANOTHER one of your oh-so-important secrets?', 'NONE'],
['dialogue', 's3_102_royal order', 'Royal Order', '... ', 'NONE'],
['dialogue', 's3_103_turning page', 'Turning Page', 'Mom and Dad continued to argue. They just kept getting angrier and angrier, until--', 'NONE'],
['dialogue', 's3_104_fair_devotion', 'Fair Devotion', '--until I took the sword that was lying at the scene and struck Royal Order in the side. That resulted in him being knocked into the statue... and him dying.', 'NONE'],
['dialogue', 's3_105_luna', 'Luna', 'BE STILL!', 'NONE'],
['dialogue', 's3_106_luna', 'Luna', 'Ms. Devotion! Turning Page! That last thing Royal Order said, about what the Guard demanded of him... Elaborate on that! At once!', 'NONE'],
['dialogue', 's3_107_athena', 'Athena', 'P-Prosecutor Luna?!', 'NONE'],
['dialogue', 's3_108_fair_devotion', 'Fair Devotion', 'I would if I could, Your Highness, but truthfully I didn\'t know what exactly he was referring to.', 'NONE'],
['dialogue', 's3_109_turning page', 'Turning Page', 'M-Me, either, Princess Luna. Sorry...', 'NONE'],
['dialogue', 's3_110_luna', 'Luna', 'Gggnnrgh...', 'NONE'],
['dialogue', 's3_111_athena', 'Athena', '(Whoa, what gives? Does Luna think she knows what Royal Order was alluding to?)', 'NONE'],
['dialogue', 's3_112_athena', 'Athena', '(Agh, never mind that! Fair interrupted Turning just now. That\'s gotta have been on purpose!)', 'NONE'],
['dialogue', 's3_113_athena', 'Athena', 'Turning! I want to hear what happened after the argument, in your own words. Without your mother interrupting you!', 'NONE'],
['dialogue', 's3_114_turning page', 'Turning Page', '... ', 'NONE'],
['dialogue', 's3_115_athena', 'Athena', '(Shoot! He\'s clammed up again! How can I convince him to talk?!)', 'NONE'],
['dialogue', 's3_116_fair_devotion', 'Fair Devotion', 'Pestering him won\'t change the facts, Ms. Cykes! It is exactly as I have said it to be--I attacked Royal Order and killed him using Turning\'s sword. ', 'NONE'],
['dialogue', 's3_117_fair_devotion', 'Fair Devotion', 'Nothing else needs to be explained!', 'NONE'],
['dialogue', 's3_118_athena', 'Athena', 'OBJECTION! Nothing, you say? Then what about the fact that Turning was later found BEHIND the victim on the crossroads?!', 'NONE'],
['dialogue', 's3_119_fair_devotion', 'Fair Devotion', 'That is entirely inconsequential to this trial! I\'ll say it again: this trial is to determine Sweetie Belle\'s guilt or innocence. My confession proves the latter.', 'NONE'],
['dialogue', 's3_120_fair_devotion', 'Fair Devotion', 'This trial has gone on long enough with you attempting to take our focus off of that. I DEMAND that this comes to an end, here and now!', 'NONE'],
['dialogue', 's3_121_judge', 'Judge', 'I\'m afraid YOU cannot determine that for us, Ms. Devotion. The court will decide that when we believe it is most appropriate.', 'NONE'],
['dialogue', 's3_122_luna', 'Luna', 'You also seem to have forgotten that we are still, technically, in the middle of your therapy session. ', 'NONE'],
['dialogue', 's3_123_luna', 'Luna', 'Ms. Cykes chose to interrupt it to both request an analysis and hear from your son.', 'NONE'],
['dialogue', 's3_124_luna', 'Luna', 'However! Said therapy session was not brought to its conclusion, and thus, MUST continue!', 'NONE'],
['dialogue', 's3_125_fair_devotion', 'Fair Devotion', 'That doesn\'t matter at this point!', 'NONE'],
['dialogue', 's3_126_luna', 'Luna', 'OBJECTION! To you, perhaps not. The same cannot be said for myself and the defense, though. Am I correct, Ms. Cykes?', 'NONE'],
['dialogue', 's3_127_athena', 'Athena', 'Completely! ', 'NONE'],
['dialogue', 's3_128_fair_devotion', 'Fair Devotion', 'Grr... Fine! Then you leave me no choice, Prosecutor Luna!', 'NONE'],
['dialogue', 's3_129_luna', 'Luna', '... What do you mean by that, Ms. Devotion?', 'NONE'],
['dialogue', 's3_130_fair_devotion', 'Fair Devotion', 'I ask that you rest your case and let the defense win. Otherwise... I\'ll reveal to the court EXACTLY what Royal Order\'s been doing in Canterlot for the past year.', 'NONE'],
['dialogue', 's3_131_twilight', 'Twilight', '!!', 'NONE'],
['dialogue', 's3_132_judge', 'Judge', '!!', 'NONE'],
['dialogue', 's3_133_athena', 'Athena', '!! W-What are you--', 'NONE'],
['dialogue', 's3_134_luna', 'Luna', 'I beg your pardon?!', 'NONE'],
['dialogue', 's3_135_private_eye', 'Private Eye', 'HOLD IT! ', 'NONE'],
['dialogue', 's3_136_private_eye', 'Private Eye', 'M-Ms. Devotion, please! You must think about what you\'re doing!', 'NONE'],
['dialogue', 's3_137_fair_devotion', 'Fair Devotion', 'Trust me, Detective, I already have. I am merely hoping that Prosecutor Luna does the same.', 'NONE'],
['dialogue', 's3_138_luna', 'Luna', '... Ms. Devotion. Do you really know of what you speak? ', 'NONE'],
['dialogue', 's3_139_fair_devotion', 'Fair Devotion', 'I do. And... I know that Royal Order was set to become the next captain of the Royal Guard for this very reason.', 'NONE'],
['dialogue', 's3_140_twilight', 'Twilight', 'N-no! How could she know that?!', 'NONE'],
['dialogue', 's3_141_athena', 'Athena', '(Especially since we didn\'t until yesterday?! Did Royal Order tell her?)', 'NONE'],
['dialogue', 's3_142_luna', 'Luna', 'BE STILL! It appears I may have slightly underestimated you... witness.', 'NONE'],
['dialogue', 's3_143_fair_devotion', 'Fair Devotion', 'Oh? So I\'m just "witness" to you, now?', 'NONE'],
['dialogue', 's3_144_fair_devotion', 'Fair Devotion', 'Surely you see, now, where you stand? If I know that much... Well. Rest your case, Prosecutor Luna. And I promise I won\'t speak another word of it.', 'NONE'],
['dialogue', 's3_145_private_eye', 'Private Eye', 'Ms. Devotion, please!', 'NONE'],
['dialogue', 's3_146_luna', 'Luna', 'BE STILL! Your offer is a kind one, witness. It is with only SOME measure of regret... that I must reject it.', 'NONE'],
['dialogue', 's3_147_fair_devotion', 'Fair Devotion', 'Huh?!', 'NONE'],
['dialogue', 's3_148_twilight', 'Twilight', 'P-Prosecutor Luna?', 'NONE'],
['dialogue', 's3_149_luna', 'Luna', 'Your attempts at blackmailing me into holding my tongue earn only my fury, witness, not my mercy! Therefore, it is the prosecution\'s HUMBLE request--', 'NONE'],
['dialogue', 's3_150_luna', 'Luna', '--that your therapy session continue... WITHOUT these shenanigans. ', 'NONE'],
['dialogue', 's3_151_fair_devotion', 'Fair Devotion', 'B-but what about Royal\'s--', 'NONE'],
['dialogue', 's3_152_luna', 'Luna', 'His secrets? That you would go so far as to air the dirty laundry of the deceased... It is utterly deplorable!', 'NONE'],
['dialogue', 's3_153_fair_devotion', 'Fair Devotion', '!!', 'NONE'],
['dialogue', 's3_154_luna', 'Luna', 'Regardless, witness. If you wish to reveal them to the court, so be it. But doing so will only mean you\'ll have leverage over NO PONY. ', 'NONE'],
['dialogue', 's3_155_luna', 'Luna', 'The decision is yours. Make it posthaste.', 'NONE'],
['dialogue', 's3_156_fair_devotion', 'Fair Devotion', 'I... G-gnngk! F-fine. Well played, Prosecutor Luna... Let\'s get this pointless exercise out of the way, then.', 'NONE'],
['dialogue', 's3_157_twilight', 'Twilight', 'Phew... For a moment there, I was worried Luna might give in to Fair\'s demands. Thank goodness she didn\'t.', 'NONE'],
['dialogue', 's3_158_athena', 'Athena', 'Yeah...', 'NONE'],
['dialogue', 's3_159_athena', 'Athena', '(Still... Luna\'s changed, in that small moment. She\'s almost enraged, like a caged animal. She wasn\'t calling Fair\'s bluff, either...)', 'NONE'],
['dialogue', 's3_160_athena', 'Athena', '(It was more like she didn\'t care what Fair had to reveal, so long as it meant we could get to the truth unobstructed.) ', 'NONE'],
['dialogue', 's3_161_athena', 'Athena', '(Like she had nothing to lose and everything to gain...?)', 'NONE'],
['dialogue', 's3_162_athena', 'Athena', '(I know that\'s good for us, but... why does it frighten me?)', 'NONE']
];

model_path = "models/vosk-model-small-en-us-0.15"
audio_filename = "audio/TS_208.wav"
activeChar = "Twilight"

model = Model(model_path)
wf = wave.open(audio_filename, "rb")
rec = KaldiRecognizer(model, wf.getframerate())
rec.SetWords(True)

# get the list of JSON dictionaries
results = []
# recognize speech using vosk model
while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        part_result = json.loads(rec.Result())
        results.append(part_result)
part_result = json.loads(rec.FinalResult())
results.append(part_result)

# convert list of JSON dictionaries to list of 'Word' objects
list_of_Words = []
for sentence in results:
    if len(sentence) == 1:
        # sometimes there are bugs in recognition 
        # and it returns an empty dictionary
        # {'text': ''}
        continue
    for obj in sentence['result']:
        w = custom_Word.Word(obj)  # create custom Word object
        list_of_Words.append(w)  # and add it to list

wf.close()  # close audiofile

# output to the screen

strLines = ""
wLines = []
charArr = []
uniqueID = []

for word in list_of_Words:
    strLines+=(" "+word.get_word())
    wLines.append(word)
    charArr.append(len(strLines)) 

print(strLines)

for x in sceneData:
    if x[0] == "dialogue":
        if x[2] == activeChar:

            #make the dialogue from scene data all lowercase and strip punctuation
            stripString = x[3].lower().translate(str.maketrans('', '', string.punctuation))
            #print(stripString)

            if not stripString:
                continue

            #fuzzy substring matching, gets all takes from strLines
            matches = find_near_matches(stripString, strLines, max_substitutions=15, max_insertions=0, max_deletions=0, max_l_dist=0)
            #print([strLines[m.start:m.end] for m in matches])                         #prints takes text
            #print([m.start for m in matches])                                        #prints indexes for the start char for each take
            #print([m.end for m in matches])                                          #prints indexes for the end char for each take
            #print([wLines[bisect(charArr, m.start)].get_word() for m in matches])     #gets word object
            #print([wLines[bisect(charArr, m.end-1)].get_word() for m in matches])       #gets word object

            for m in matches:

                maxMatches = 3

                if len(matches) > maxMatches:
                    del matches[maxMatches:len(matches)]

                start = wLines[bisect(charArr, m.start)].get_start()-0.1
                end = wLines[bisect(charArr, m.end-1)].get_end()+0.1
                print(str(start) + "/" + str(end) + "/" + x[1])

                if x[1] not in uniqueID:
                    uniqueID.append(x[1])
                    #print(x[1])

for x in sceneData:
    if x[2] == activeChar:
        if x[1] not in uniqueID:
            print("Failed line: " + x[1])