const apolloDictionary = new Map([
[`You guys get going. I’ll stay here with Rarity.`, `Neutral`],
[`I said so, didn’t I? What’s the matter?`, `Serious`],
[`Hey, come on. I don’t hate everything about this world, y’know? `, `Neutral`],
[`And besides, I’d like to help out Rarity. Even if it’s just a bit of legal advice, I’ll do what I can.`, `Neutral`],
[`It’s not like that! Like I said, I don’t hate everything here. `, `Shock`],
[`Rarity, for instance. She’s… what’s the word? Refined! She takes herself seriously. I can appreciate that. `, `Serious`],
[`R-right...`, `Weary`],
[`All right. Sounds good, Apollo. We’ll meet up with you later at the Everfree Forest, then.`, `Weary`],
[`Right! Good luck, you guys! I’ll see you there!`, `Neutral`],
[`Hey, come on, let me in! I’m a lawyer, too!`, `Determined`],
[`What? That’s ridiculous!`, `Serious`],
[`Hey, Apollo!`, `Serious`],
[`Oh, hey! You guys made it!`, `Neutral`],
[`No, I just got here. `, `Serious`],
[`But these guards won’t let me pass! I even showed them that silly badge and everything!`, `Weary`],
[`Agh, less productive than I would have liked.`, `Sad`],
[`I did my best to calm Rarity and Sweetie Belle down, but I didn’t get much more information out of the latter. `, `Serious`],
[`She seemed really shaken up by everything, so I didn’t want to push it.`, `Serious`],
[`I take it that the investigation hasn’t been very fruitful on your end, either?`, `Introspective`],
[`Not really, no. We learned a bit more about Royal Order from Fair Devotion, but not much else.`, `Introspective`],
[`Seems like both sides aren’t being very forthcoming, for one reason or another.`, `Serious`],
[`Ugh... This investigation is looking like it’s reaching a dead end… `, `Serious`],
[`Maybe not, Athena. I might not have gotten any new info directly, but I did notice one thing.`, `Neutral`],
[`Yeah. Sweetie Belle’s got a tell. Did you notice it?`, `Confident`],
[`Uh… No, I can’t say I did. That’s kind of your department, buddy.`, `Confident`],
[`Right on the money, Trucy.`, `Confident w/Hand Movement`],
[`Oh yeah, now that you mention it, she did do that an awful lot, didn’t she?`, `Confident`],
[`Do you think that means she’s hiding something?`, `Introspective`],
[`She definitely is. But it was difficult to say what exactly, or what triggered that tell in the first place.`, `Introspective`],
[`And with how frantic she was, it didn’t feel right to push her on it.`, `Introspective`],
[`Why am I not surprised that I’M the bait? `, `Weary`],
[`Maybe that wasn’t the best question.`, `Weary`],
[`Anyway, what exactly would I do as “bait”? `, `Serious`],
[`Make a scene and just hope they don’t pay attention to the other three humans just hanging around here?`, `Serious`],
[`Yeah! That way, I can suplex the other one! `, `Serious`],
[`With both of them out of commission, we’d be able to sneak past, easy-peasy!`, `Serious`],
[`Is that your answer to everything...?`, `Weary`],
[`I was JOKING, Apollo! Jeez! Learn to lighten up, would you? `, `Weary`],
[`Ugh. Regardless, we have to do something. `, `Serious`],
[`Private Eye isn’t here, and we can’t exactly stand around waiting for him. `, `Serious`],
[`We NEED his help!`, `Serious`]
]);

module.exports = apolloDictionary;