const phoenixDictionary = new Map([
["?!", "Serious"],
["Neither of you did anything wrong. All you did was point out what the evidence said. It just so happens that one of our friends got caught in the crossfire.", "Neutral"],
["That’s a good idea, Twilight. But where would we start?", "Thinking"],
["We can’t say that for certain just yet. Regardless… that should be everything we know so far.", "Thinking"],
["We’ll cross that bridge when we get to it. What else?", "Weary"],
["Of course!", "Smile"],
["Trucy, we’re already bringing enough people as it is. I think you should just— ", "Weary"],
["… All right. I can’t say no to that face. Just behave yourself.", "Smile"],
["Then, on that note, I think that’s everyone. It’ll make for a somewhat crowded detention center, but that can’t be helped.", "Smile"],
["I guess that means we’d better go talk to them later, then.", "Thinking"],
["Then we should do just that. Let’s go, everyone.", "Mysterious"],
["I… think she’s just surprised that you’re being so casual about hanging around anywhere but the castle, I guess.", "Abashed"],
["She decided to stay there, along with Apollo, for when Sweetie Belle is released.", "Serious"],
["Hang on a second. Does that mean Luna was aware that the magazines might have been planted in your house?", "Thinking"],
["Which led to us learning that Diamond Tiara had planted the magazines here.", "Thinking"],
["Not until Sonata and Private Eye revealed it to her after the trial, in any case.", "Thinking"],
["A… travel case?", "Thinking"],
["Yeah, Trucy?", "Smile"],
["The… date? Well, it’s February 14th. Why?", "Thinking"],
["Well, that was… abrupt.", "Weary"],
["Are you thinking that she might be involved in his death?", "Serious"],
["Hold on a moment, you three. I think you should see this.", "Serious"],
["While Twilight and Athena were busy talking to the girls, I noticed something in Diamond Tiara’s trash can.", "Thinking"],
["[Awkward] You make it sound like I’m some sort of chatterbox.", "Abashed"],
["Just a hunch I had. I managed to take a quick picture of what was in it before we left. Look.", "Smile"],
["I can’t really tell. I had to snap it quickly before they noticed. It definitely looks like one of those gossip magazines about you girls.", "Thinking"],
["If I didn’t have to sneak the shot, I might have gotten a better angle, or a peek at what was in it.", "Sad"],
["In any case, I don’t think this is a coincidence. We’ll definitely have to look into this more.", "Serious"]
])

module.exports = phoenixDictionary;